# Generated by Django 3.2.4 on 2021-06-28 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20210628_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
