# Generated by Django 3.2.4 on 2021-06-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210628_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='user',
        ),
    ]
