# Generated by Django 3.2.4 on 2021-06-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_project_projects_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='profect_title',
            new_name='project_title',
        ),
    ]
