# Generated by Django 3.2.4 on 2021-07-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_htmlproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlproject',
            old_name='project_code_html_js',
            new_name='project_code_html',
        ),
        migrations.AddField(
            model_name='htmlproject',
            name='project_code_js',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
