# Generated by Django 3.2.4 on 2021-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_exercise', '0002_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='help',
            field=models.TextField(blank=True),
        ),
    ]
