# Generated by Django 3.2.4 on 2022-05-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_auto_20220527_1027'),
        ('python_exercise', '0003_exercise_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='lessons.lessons'),
        ),
    ]
