# Generated by Django 3.2.4 on 2021-06-14 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210614_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 6, 14, 14, 55, 44, 379854, tzinfo=utc), max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.category'),
        ),
    ]
