# Generated by Django 3.2.4 on 2021-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='code',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='code',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='video',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to='Lesson'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(upload_to='Lessons'),
        ),
    ]
