# Generated by Django 3.2.4 on 2021-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20210618_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, upload_to='Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(blank=True, upload_to='Lessons'),
        ),
    ]
