# Generated by Django 3.2.4 on 2021-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20210623_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
