# Generated by Django 3.2.4 on 2021-06-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='page_layout',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
