# Generated by Django 3.2.4 on 2021-06-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_page_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
