# Generated by Django 3.2.4 on 2021-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_lesson_code_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='page_layout',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_python',
            field=models.TextField(blank=True),
        ),
    ]
