# Generated by Django 3.2.4 on 2021-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20210624_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='image',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
