# Generated by Django 3.2.4 on 2021-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_auto_20210625_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code_js',
            field=models.TextField(blank=True),
        ),
    ]
