# Generated by Django 3.2.4 on 2021-07-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_lesson_code_js'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
    ]
