# Generated by Django 3.2.4 on 2021-08-01 20:57

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_embededvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='embededvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
